name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Based on https://hexdocs.pm/elixir/compatibility-and-deprecations.html
          - {elixir: "1.19.x", otp: "28.x"}
          - {elixir: "1.19.x", otp: "27.x"}
          - {elixir: "1.19.x", otp: "26.x"}
          - {elixir: "1.18.x", otp: "27.x"}
          - {elixir: "1.18.x", otp: "26.x"}
          - {elixir: "1.18.x", otp: "25.x"}
          - {elixir: "1.17.x", otp: "27.x"}
          - {elixir: "1.17.x", otp: "26.x"}
          - {elixir: "1.17.x", otp: "25.x"}
          - {elixir: "1.16.x", otp: "26.x"}
          - {elixir: "1.16.x", otp: "25.x"}
          - {elixir: "1.16.x", otp: "24.x"}
          - {elixir: "1.15.x", otp: "26.x"}
          - {elixir: "1.15.x", otp: "25.x"}
          - {elixir: "1.15.x", otp: "24.x"}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix caches
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('mix.exs', 'lib/**/*.ex', 'test/**/*.exs', '.formatter.exs') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Check formatting
        run: mix format --check-formatted

      - name: Lint
        run: MIX_ENV=test mix compile --warnings-as-errors

      - name: Run tests
        run: MIX_ENV=test mix test
